eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  output:
    ansi:
      enabled: ALWAYS

okta:
  oauth2:
    issuer: https://dev-80910482.okta.com/oauth2/default
    audience: api://default
